dataset:
  test:
    class: CoDesignDataset
    mmap_dir: ./datasets/pepbdb/processed
    specify_index: ./datasets/pepbdb/processed/train_index.txt
    backbone_only: false

dataloader:
  num_workers: 2
  batch_size: 32

backbone_only: false
